# Generated by Django 5.0.3 on 2024-04-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_discount_price_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
